Revert "PixeldustSystemUI: switch to ProtonAOSP UDFPS HBM provider"
This reverts commit fed2db57f3106ff225f1f856bafe507839a9ffc8.

vendor/pixelstyle/app_override/PixeldustSystemUI/src/com/pixeldust/android/systemui/biometrics/PixeldustUdfpsHbmProvider.kt:71:36: error: operator '==' cannot be applied to 'Un
it?' and 'Boolean'
        if (hbmType != HBM_TYPE || displayHal?.let { it.lhbmState } == true) {
                                   ^
vendor/pixelstyle/app_override/PixeldustSystemUI/src/com/pixeldust/android/systemui/biometrics/PixeldustUdfpsHbmProvider.kt:71:57: error: unresolved reference: lhbmState
        if (hbmType != HBM_TYPE || displayHal?.let { it.lhbmState } == true) {
                                                        ^
vendor/pixelstyle/app_override/PixeldustSystemUI/src/com/pixeldust/android/systemui/biometrics/PixeldustUdfpsHbmProvider.kt:94:21: error: unresolved reference: lhbmState
        displayHal?.lhbmState = true
                    ^
vendor/pixelstyle/app_override/PixeldustSystemUI/src/com/pixeldust/android/systemui/biometrics/PixeldustUdfpsHbmProvider.kt:114:35: error: unresolved reference: lhbmState
        displayHal?.let { if (!it.lhbmState) return }
                                  ^
vendor/pixelstyle/app_override/PixeldustSystemUI/src/com/pixeldust/android/systemui/biometrics/PixeldustUdfpsHbmProvider.kt:118:25: error: unresolved reference: lhbmState
            displayHal?.lhbmState = false
                        ^

Signed-off-by: spezi77 <spezi7713@gmx.net>